# Generated by Django 6.0.4 on 2026-06-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='prefix',
            field=models.CharField(db_index=True, max_length=12),
        ),
    ]
